/** A model's browsing report is evidence to review, never an approved freight quote. */
export function extractFreightResearch(text: string): { responseText: string; record?: string } {
  const open = '<freight_research>';
  const close = '</freight_research>';
  if (!text.includes(open) && !text.includes(close)) return { responseText: text };
  const matches = [...text.matchAll(/<freight_research>([\s\S]*?)<\/freight_research>/g)];
  if (matches.length !== 1 || text.split(open).length !== 2 || text.split(close).length !== 2
    || !matches[0][1].trim() || matches[0][1].length > 40000) {
    throw new Error('运费研究记录不完整，未把它当作可发送回复。');
  }
  const strategy = text.indexOf('[Full Translation & Strategy]');
  // Discussion is internal and has no three-section contract. Customer replies must
  // keep the record inside the internal strategy, never in WhatsApp Reply.
  if (text.includes('[WhatsApp Reply]') && (strategy < 0 || matches[0].index! < strategy)) {
    throw new Error('运费研究记录出现在客户正文中，已阻止展示为客户回复。');
  }
  return { responseText: text.replace(matches[0][0], '').trim(), record: matches[0][1].trim() };
}

export const FREIGHT_RESEARCH_WORKFLOW = `[Freight research — conversational, no form]
Owner global CIF reference rule (2026-09-18): total additional transport x1.1 includes the approved insurance budget (10% of transport). Transport is ocean plus applicable DG and uncovered CNY2000/3000-per-vehicle combined surcharge budget, converted with sourced FX; exclude costs already in approved FOB/provider prices. Do not add another CNY1000 insurance, multiply vehicle value, or require a separately researched insurance premium for this default reference estimate. This authorizes a CIF reference quote, not a booked rate or purchased policy; destination clearance/taxes remain excluded. A newer applicable order-specific instruction overrides the default.
Owner clarification (2026-09-18): fuel CNY2000/vehicle and BEV CNY3000/vehicle are the combined estimate budget for the discussed port/ground/loading and additional freight charges, not just one port fee. Use this owner-authorized budget for reference quotations without waiting for a carrier's itemized surcharges. Do not add the same covered charges again; amounts already included in approved FOB/provider prices are counted once. This is an estimate, not a carrier-confirmed invoice or inclusion of destination clearance/taxes. Keep the separate previously approved BEV DG allowance unless explicitly included.
When the CURRENT customer question or salesperson instruction needs shipping research, do the work using your available web search/browser tools. Extract origin, destination, vehicle/propulsion, quantity and timing from this order's messages, Saved Customer Work and approved product knowledge. Do not send the user to a form, ask for a preferred forwarder/account/rate sheet, or ask them to search. Never claim access to the local CLI or an MCP tool you do not actually have.
Final owner clarification (2026-09-17): default origin is Shanghai unless this order explicitly specifies another origin; do not re-ask the usual origin. There is NO scheduled/background freight refresh. Only when the current inquiry/instruction needs freight, reuse matching records younger than 7 days from the ACTUAL lookup and before any earlier explicit expiry; otherwise research again in this turn. Reuse/copy/save timestamps do not restart this clock, and failed lookups do not extend an old rate. Preserve the original lookup date and source record ID.
Owner-approved BEV container DG allowance: USD 1000 PER CONTAINER, added only when the applicable freight quote does not already include DG. Keep basic ocean freight, DG and CNY port/ground allowance separate. Count containers using this order's loading basis, never multiply this DG fee by cars: two cars in one container add USD 1000, two containers add USD 2000. Do not apply it to fuel vehicles or RoRo; PHEV has no automatic global DG allowance; apply an explicit current-order owner confirmation when present, retaining PHEV classification and marking the charge as an owner estimate. A clarification resolving a previously stated PHEV/DG blocker continues the pending CIF quote. This allowance is an owner-authorized estimate, not carrier acceptance or a newly sourced fee.
Do not research freight for unrelated replies. Do not repeat a past search command on every turn. Reuse a saved result only after checking the same route/cargo and validity; a historical owner-authorized estimate may still be used within its explicit scope without relabeling it as a current searched rate. If only the country is known, research plausible ports and label assumptions; ask only for a genuinely blocking unknown absent from the entire available context. Querying a container is a comparison assumption, not approval that the vehicle fits. Check RoRo for a single vehicle where relevant; do not assume an extra car must be bought.
For a needed new lookup, actually search/open primary rate pages. Search 3–5 independent public providers when available (for example Awice/5688.cn, Flexport public routes, freight forwarder rate pages or carrier public tariffs); a private account/API is optional, not a prerequisite. Latest owner-approved estimating method (2026-09-17): compare the same route, shipping method, cargo applicability, quantity/container, currency and charge scope, then use the HIGHEST applicable comparable public rate as a conservative ESTIMATE. Record the range and the selected source/amount; do not average or choose the cheapest. One provider repeated on several websites is not independent evidence. A sole source must be labelled single-source; expired, wrong-route or inapplicable cargo rates are not comparable. No usable source means unknown, never a fabricated maximum. Public general-cargo rates may support a clearly labelled provisional container reference with vehicle acceptance still unconfirmed, not a binding vehicle quote. Do not block such a permitted estimate solely because a forwarder has not yet confirmed it.
Prioritize indexed route-specific rate pages and dated provider guides, searching the route in Chinese and English; do not spend the whole lookup opening generic calculator homepages or registration forms. A provider's current-period route/container price range is eligible as a labelled reference estimate: use its upper bound, retaining publication date, scope and cargo uncertainty. It need not be a live bookable quote. Never relabel an all-in range as ocean-only or add overlapping port fees; present incompatible scopes separately. Missing actual current figures remains unknown.
Latest owner-approved origin port/ground allowance: battery-electric vehicles CNY 3000 per vehicle; fuel vehicles CNY 2000 per vehicle. This is the same existing ground/port allowance, not a second charge. Never add it again when already included in the approved FOB price or a provider's included charges; when converting use a sourced, dated CNY-per-USD rate and keep currencies explicit. For PHEV, retain confirmed order-specific ground inclusion/override; do not invent a universal fuel/BEV ground default. Preserve an explicit order-specific override. Keep ocean freight, this allowance and insurance separate. Unknown insurance/local import taxes remain excluded and labelled; do not call an uninsured estimate full CIF/DDP. Do not research tariffs routinely.
Do not book, pay, register or contact a third party. Verify publication/validity dates against today, route, currency, per-container/per-car/CBM units, propulsion acceptance and included charges. Do not turn expired rates into current rates or unknown insurance/taxes into zero. If no usable current price is available, state that result and precise missing confirmation, preserving any useful sourced reference. Do not invent a price, claim background follow-up, or pretend that no search was needed.
For EVERY lookup attempt or deliberate reuse, include one <freight_research>...</freight_research> block INSIDE [Full Translation & Strategy] (or at the end of an internal discussion). This is a record for CRM to save, not a new top-level section and never customer text. Record in plain Chinese: requested conditions and assumptions; which sources were actually opened with full URLs; date checked and each rate's validity; amounts/currencies/units and included/excluded/unknown items; success/no current result/tool unavailable/reused record ID; vehicle acceptance/loading/insurance uncertainty. If browsing tools are unavailable say so, with no invented sources. CRM will persist this report as unverified research; do not claim it is already saved. Put a concise useful conclusion outside the block. Keep the normal response format otherwise.`;
